version: '3.9'

services:

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    networks:
      - kafka_-net

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
    networks:
      - kafka_-net

  mysql:
    image: mysql:8.0.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./mysql_product_management:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql-net

  pms-original:
    container_name: pms-original
    image: pms-original
    restart: always
    build: ./product_management_system_original
    depends_on:
      - mysql
      - kafka
    ports:
      - "10000:10000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: product-management-original
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_BROKERCONNECT: "kafka:29092"
    networks:
      - mysql-net
      - kafka_-net
    volumes:
      - ./product_management_system_original/src/main/resources/static/images:/app/images

  pms-kafka:
    container_name: pms-kafka
    image: pms-kafka
    restart: always
    build: ./product_management_system_kafka
    ports:
      - "10001:10000"
    depends_on:
      - mysql
      - kafka
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: product-management-kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_BROKERCONNECT: "kafka:29092"
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
    networks:
      - mysql-net
      - kafka_-net

  pms-frontend:
    build:
      context: ./product_management_system_frontend
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    container_name: pms-frontend
    volumes:
      - ./product_management_system_frontend:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules

networks:
  kafka_-net:
    driver: bridge
  mysql-net:
    driver: bridge

